import json

# Comprehensive extraction of all 250 questions from the PDF OCR
# Grouped by Unit (50 questions each)
# Answers based on the Complete Answer Key at the end of the PDF

def get_math_data():
    units = []

    # UNIT 1: COMPLEX NUMBERS (Q1-Q50)
    u1_questions = [
        {"q": "Which complex number is purely imaginary?", "options": ["3+0i", "0-2i", "4", "None"], "answer": 1},
        {"q": "Additive identity of complex numbers is:", "options": ["1+0i", "0+1i", "0+0i", "None"], "answer": 2},
        {"q": "Conjugate of -3+4i is:", "options": ["-3-4i", "-3+4i", "3+4i", "3-4i"], "answer": 0},
        {"q": "Value of i⁴ is:", "options": ["1", "-1", "i", "-i"], "answer": 0},
        {"q": "For Z=2+5i, value of |conjugate Z|²:", "options": ["4", "25", "29", "None"], "answer": 2},
        {"q": "Reciprocal of -2+√2i is:", "options": ["(-2+√2i)/6", "(-2-√2i)/6", "(-2+√2i)/-6", "(-2-√2i)/-6"], "answer": 1},
        {"q": "Argument of z = -1-√3i is:", "options": ["π/3", "2π/3", "-2π/3", "π"], "answer": 2},
        {"q": "Let z be complex with |z|=4 and arg(z)=5π/6, then z=?", "options": ["-2√3+2i", "2√3+2i", "-2√3-2i", "√3-i"], "answer": 0},
        {"q": "Value of (3y-2)+i(7-2x)=0 for x,y is:", "options": ["x=7/2, y=2/3", "x=2/3, y=7/2", "x=7, y=2", "None"], "answer": 0},
        {"q": "Square root of -i is:", "options": ["±(1-i)/√2", "±(1+i)/√2", "±(1-i)", "±i"], "answer": 0},
        {"q": "Real part of √(9+√-16) is:", "options": ["3", "0", "√2", "None"], "answer": 1},
        {"q": "Real part of iⁱ is:", "options": ["0", "e^(-π/2)", "1", "π"], "answer": 1},
        {"q": "Polar form of √5+√-16:", "options": ["3e^(π/2)", "3e^(-π/2)", "2e^(π/2)", "None"], "answer": 0},
        {"q": "Imaginary part of (x-1)/(3+i) is (x-1 real):", "options": ["(x-1)/10", "-(x-1)/10", "(x+1)/10", "None"], "answer": 1},
        {"q": "Express (-3) in polar form:", "options": ["3(cosπ+i sinπ)", "3(cos0+i sin0)", "3(cos2π+i sin2π)", "None"], "answer": 0},
        {"q": "Modulus of (1+i)/[(1-i)(1+i)]⁻¹ is:", "options": ["2", "1", "√2", "4"], "answer": 1},
        {"q": "Number of solutions of z² = z̄ is:", "options": ["2", "3", "4", "1"], "answer": 1},
        {"q": "Conjugate of -1+√-2 lies in quadrant:", "options": ["I", "II", "III", "IV"], "answer": 0},
        {"q": "Value of (z+3)(z̄+3) if |z|=3:", "options": ["|z+3|²", "9", "|z|+3", "None"], "answer": 0},
        {"q": "Locus of |z-2|=|z+3| is:", "options": ["x=−1/2", "y=−1/2", "x=1/2", "y=1/2"], "answer": 0},
        {"q": "Euler's exponential form of sinθ is:", "options": ["(eⁱᶿ - e⁻ⁱᶿ)/(2i)", "(eⁱᶿ + e⁻ⁱᶿ)/2", "eⁱᶿ/2", "None"], "answer": 0},
        {"q": "If θ is principal value of tan⁻¹x, general value is:", "options": ["nπ+θ", "2nπ+θ", "nπ+(-1)ⁿθ", "None"], "answer": 0},
        {"q": "Which is true: cos(hx) = cosx?", "options": ["cosh x = i cos x", "cosh x = cos ix", "Both A&B", "None"], "answer": 1},
        {"q": "If z=a+ib is complex, Re(z) is:", "options": ["a", "-a", "b", "-b"], "answer": 0},
        {"q": "Argument of (1+i)⁴ is:", "options": ["π", "π/4", "π/2", "2π"], "answer": 0},
        {"q": "Modulus of z = a+ib is:", "options": ["√(a²+b²)", "a²+b²", "a+b", "None"], "answer": 0},
        {"q": "If (x+iy)/(a+ib) = (7+9i), find x,y:", "options": ["(7,9)", "(-7,9)", "(9,-7)", "None"], "answer": 0},
        {"q": "a+bi and a-bi are said to be:", "options": ["Conjugate", "Additive inverse", "Factors", "Multiplicative inverse"], "answer": 0},
        {"q": "Solve z² - 8 = i(7-2z); answer in x+iy:", "options": ["3-2i", "4+3i", "3+2i", "4-3i"], "answer": 0},
        {"q": "Square root of 1+i√3 is:", "options": ["±(1/√2)(√6+i√2)", "±(√6-i√2)/2", "±(√6+i√2)/2", "None"], "answer": 2},
        {"q": "Find value of tan⁻¹(4/3)+tan⁻¹(3/5)-tan⁻¹(8/19):", "options": ["π/4", "3π/4", "π", "None"], "answer": 0},
        {"q": "Find tan⁻¹(√3)-sec⁻¹(-2):", "options": ["-π/3", "π/3", "π", "None"], "answer": 0},
        {"q": "Solve (1)^(1/4):", "options": ["1,-1,i,-i", "1,2,-1,-i", "1,-1", "None"], "answer": 0},
        {"q": "Modulus of z=1-i is:", "options": ["√2", "2", "1", "None"], "answer": 0},
        {"q": "General value of log(e²):", "options": ["2nπi+2", "2nπi-2", "2nπ+2i", "None"], "answer": 0},
        {"q": "Value of e^(log(5+9i)):", "options": ["5+9i", "5-9i", "9+5i", "None"], "answer": 0},
        {"q": "Range of sin⁻¹x is:", "options": ["[-π/2, π/2]", "[0, π]", "(-π, π)", "None"], "answer": 0},
        {"q": "Value of tan⁻¹(b/a) - tan⁻¹((a-b)/(a+b)) is:", "options": ["π/4", "π/3", "π/2", "None"], "answer": 0},
        {"q": "Value of tan⁻¹(b/a):", "options": ["arctan(b/a)", "π+arctan(b/a)", "Both", "None"], "answer": 2},
        {"q": "Square of complex number (-2+2√3i) is:", "options": ["4+12i", "4-8√3i", "-8+8√3i", "None"], "answer": 2},
        {"q": "Trigonometric form of 1-i is:", "options": ["√2(cos(-π/4)+i sin(-π/4))", "√2(cosπ/4+i sinπ/4)", "√2(cos(3π/4)+i sin(3π/4))", "None"], "answer": 0},
        {"q": "Which of the following product has conjugate Real&Positive:", "options": ["Imaginary&Positive", "Real&Negative", "Real&Positive", "Imaginary&Negative"], "answer": 2},
        {"q": "If z1=(1+i), z2=(2+i), z3=(3+i), conjugate of z1z2/z3 is:", "options": ["1+3i/5", "1-3i/5", "(1+3i)/5", "(1-3i)/5"], "answer": 3},
        {"q": "Region defined by |z|>1 on Argand plane is:", "options": ["x²+y²≥1", "x+y=1", "x²+y²≤1", "x²+y²=1"], "answer": 0},
        {"q": "Which powers of i equal 1?", "options": ["i⁴", "i⁸", "i⁰", "All above"], "answer": 3},
        {"q": "Reciprocal of z = a+ib is:", "options": ["z̄/|z|²", "z/|z|²", "1/z̄", "None"], "answer": 0},
        {"q": "Commutative property NOT true for complex numbers in:", "options": ["Addition", "Multiplication", "Subtraction&Division", "None"], "answer": 2},
        {"q": "Which property holds: z1+z2 = z2+z1?", "options": ["Commutative", "Associative", "Distributive", "None"], "answer": 0},
        {"q": "Real and imaginary part of log(i) are:", "options": ["0, π/2", "π/2, 0", "1, π/2", "None"], "answer": 0},
        {"q": "Value of (±i·π/2) exponential:", "options": ["±i", "i", "±1", "None"], "answer": 0}
    ]

    # UNIT 2: VECTOR CALCULUS (Q1-Q50)
    u2_questions = [
        {"q": "cos a·cos b·i + cos a·cos b·j + sin a·k is:", "options": ["null vector", "unit vector", "constant vector", "None"], "answer": 1},
        {"q": "If vector l-2xj+2yk is perpendicular to l+2xj-3yk, locus of (x,y) is:", "options": ["circle", "parabola", "ellipse", "hyperbola"], "answer": 0},
        {"q": "If vectors 3i+aj+k and 2i-j+8k are perpendicular, value of a is:", "options": ["14", "-14", "7", "1/7"], "answer": 1},
        {"q": "If θ is angle between a and b, then a·b≥0 only when:", "options": ["0≤θ≤π/2", "0<θ<π/2", "0≤θ≤π", "0<θ≤π/2"], "answer": 0},
        {"q": "If a is non-zero scalar, then ka is unit vector if:", "options": ["k=1", "k=-1", "k=1/|k|", "a=1/|k|"], "answer": 2},
        {"q": "If i,j,k are unit vectors, then i·j=?", "options": ["ixj=1", "i·i=1", "i·j=0", "None"], "answer": 2},
        {"q": "Particle moves along x=2t², y=t²-4t, z=3t-5. Velocity at t=1:", "options": ["4i-2j+3k", "2i-2j+k", "4i+2j+3k", "None"], "answer": 0},
        {"q": "If r=cos mt·i+sin mt·j, then r·(dr/dt)=?", "options": ["0", "1", "-1", "2"], "answer": 0},
        {"q": "Vector normal to surface f(x,y,z)=c is given by:", "options": ["grad f", "div f", "curl f", "None"], "answer": 0},
        {"q": "A vector field defined by F is called solenoidal if:", "options": ["div F=0", "curl F=0", "div F=constant", "curl F=constant"], "answer": 0},
        {"q": "Modulus of normal to surface z²-4x²-y² at (1,0,2) is:", "options": ["√40", "√80", "√20", "20"], "answer": 1},
        {"q": "If F is constant, then grad F is:", "options": ["1", "-1", "0", "F"], "answer": 2},
        {"q": "If A is constant vector, grad A=?", "options": ["0", "1", "2", "None"], "answer": 0},
        {"q": "Vector field V is said to be irrotational if:", "options": ["div V=0", "grad V=0", "curl V=0", "None"], "answer": 2},
        {"q": "If r=xi+yj+zk, then div r is:", "options": ["0", "1", "2", "3"], "answer": 3},
        {"q": "If r=xi+yj+zk, then curl r is:", "options": ["0", "1", "3", "None"], "answer": 0},
        {"q": "Evaluate div V at (1,2,3) for V=3x²i+5xy²j+xyz²k:", "options": ["0", "20", "80", "10"], "answer": 1},
        {"q": "If r=x·i+y·j+z·k, then ∇r²=?", "options": ["2r", "r", "2", "None"], "answer": 0},
        {"q": "If r=a sin kt+b cos kt, a,b,k are constants, then d²r/dt²=?", "options": ["0", "-k²r", "k²r", "kr"], "answer": 1},
        {"q": "Find the directional derivative of f at (1,2,-1) in direction 2i-j-2k where f=x²yz+4xz²:", "options": ["37", "17", "27", "57"], "answer": 0},
        {"q": "Greatest rate of increase of f=xyz² at point (1,0,3):", "options": ["9", "2", "3", "0"], "answer": 0},
        {"q": "Find value of a such that F=2xyz²i+αx²z²j+2x²yz·k is irrotational:", "options": ["9", "-9", "2", "3"], "answer": 0},
        {"q": "Find div V for V=x³y³+z³y+2y:", "options": ["x²y³+z³", "3x²y³+z³", "y³+z³", "None"], "answer": 0},
        {"q": "Find values of a,b,c if F=(x+2y+az)i+(bx-3y-z)j+(4x+cy+2z)k is irrotational:", "options": ["a=4,b=2,c=-1", "a=1,b=2,c=4", "a=4,b=1,c=-1", "None"], "answer": 0},
        {"q": "Magnitude of source or sink at given point is measured by:", "options": ["gradient", "divergence", "laplacian", "curl"], "answer": 1},
        {"q": "A vector perpendicular to both vectors is:", "options": ["|axb|", "axb", "a·b", "None"], "answer": 1},
        {"q": "∇f(r) is:", "options": ["f(r)r", "f'(r)r-hat", "f'(r)∇r", "None"], "answer": 1},
        {"q": "Gradient of |r²| is:", "options": ["r/2", "2r", "r", "None"], "answer": 1},
        {"q": "For solenoidal field v, divergence of v is:", "options": ["Non zero", "Zero", "Never zero", "None"], "answer": 1},
        {"q": "d/dt(axb) = ?", "options": ["ax(db/dt)+(da/dt)xb", "ax(db/dt)-(da/dt)xb", "(da/dt)xb", "None"], "answer": 0},
        {"q": "If φ(x,y,z)=x+y, then directional derivative of φ in direction i is:", "options": ["0", "1", "i", "None"], "answer": 1},
        {"q": "If curl v=0 where v=wxr, then curl v is:", "options": ["0", "1", "Not", "l"], "answer": 0},
        {"q": "If v=wxr, then curl v=?", "options": ["0", "2w", "w", "None"], "answer": 1},
        {"q": "∇²rⁿ=?", "options": ["n(n+1)rⁿ⁻²", "n(n-1)rⁿ⁻²", "nrⁿ⁻²", "None"], "answer": 0},
        {"q": "If r=√(x²+y²+z²), then ∇r is:", "options": ["r/r", "r", "1/r", "None"], "answer": 0},
        {"q": "|axb| represents:", "options": ["area of triangle", "area of parallelogram", "volume", "None"], "answer": 1},
        {"q": "∇φ is equal to:", "options": ["g∇f+f∇g", "g∇f-f∇g", "f∇g+g∇f", "None"], "answer": 0},
        {"q": "If F=x²i+y²j+z²k, what is div F?", "options": ["2(x+y+z)", "2x+2y+2z", "x+y+z", "None"], "answer": 0},
        {"q": "Arg(z1z2) at z=0 is:", "options": ["Not defined", "0", "π", "None"], "answer": 0},
        {"q": "If F=xi+yj+zk, then curl F is:", "options": ["0", "1", "2", "3"], "answer": 0},
        {"q": "Greatest rate of increase of f is in direction of:", "options": ["∇f", "curl f", "div f", "None"], "answer": 0},
        {"q": "If F = rⁿ · r, divergence of F is:", "options": ["(n+3)rⁿ", "nrⁿ", "(n+3)rⁿ⁻¹", "None"], "answer": 0},
        {"q": "Normal vector to surface F(x,y,z)=c is:", "options": ["∇F", "div F", "curl F", "None"], "answer": 0},
        {"q": "Region defined by |z|≥1 is:", "options": ["x²+y²≥1", "x+y≥1", "x²+y²≤1", "None"], "answer": 0},
        {"q": "If F=(x²y,y²z,z²x), find div F:", "options": ["2xy+2yz+2xz", "x²+y²+z²", "2(x+y+z)", "None"], "answer": 0},
        {"q": "Which is NOT true: div(A+B)=?", "options": ["N·(A+B)=N·A+N·B", "div A+div B=div(A+B)", "div(A+B)=curl(A-B)", "None"], "answer": 2},
        {"q": "Gradient of a scalar function f is:", "options": ["∂f/∂x·i+∂f/∂y·j+∂f/∂z·k", "curl f", "div f", "None"], "answer": 0},
        {"q": "For vector F, div(curl F)=?", "options": ["0", "1", "∇²F", "None"], "answer": 0},
        {"q": "∇(fg)=?", "options": ["f∇g+g∇f", "f∇g-g∇f", "g∇f", "None"], "answer": 0},
        {"q": "∇·(φA)=?", "options": ["φ∇·A+A·∇φ", "φ∇·A", "A·∇φ", "None"], "answer": 0}
    ]

    # UNIT 3: FOURIER SERIES (Q1-Q50)
    u3_questions = [
        {"q": "In Fourier series, bₙ=0 for ......... function:", "options": ["odd", "even", "both", "none"], "answer": 1},
        {"q": "What are Fourier coefficients?", "options": ["a₀, an, bn", "a₀ only", "bn only", "None"], "answer": 0},
        {"q": "Fourier coefficients in the following not present:", "options": ["bn", "an", "a₀", "all"], "answer": 0},
        {"q": "Which is NOT Dirichlet's condition for Fourier expansion?", "options": ["f is periodic", "f has finite discontinuities", "f has finite maxima and minima", "f has infinite value"], "answer": 3},
        {"q": "If f(x) is odd, then only coefficient present is:", "options": ["a₀", "an", "bn", "all"], "answer": 2},
        {"q": "What is the period of sin x?", "options": ["2π", "π", "π/2", "4π"], "answer": 0},
        {"q": "Value of a₀ if f(x)=x² is expanded in -π<x<π:", "options": ["2π²/3", "π²/3", "4π²/3", "0"], "answer": 0},
        {"q": "Find b₀ if f(x)=x-x³ in -π<x<π:", "options": ["can't be found", "0", "all bn", "None"], "answer": 1},
        {"q": "The formula used to find the Fourier coefficients is known as:", "options": ["Euler's formulae", "Cauchy formulae", "Legendre formulae", "None"], "answer": 0},
        {"q": "Value of a₀ if f(x)=x² expanded in [0,5]?", "options": ["25/4", "125/4", "5/4", "62.5/4"], "answer": 1},
        {"q": "If f(-x)=f(x), then f is:", "options": ["odd", "even", "neither", "none"], "answer": 1},
        {"q": "In Fourier series expansion of f(x)=x sin x in 0<x<2π:", "options": ["a₀=2", "a₀=-2", "bn=0", "a₀=0"], "answer": 0},
        {"q": "If f(x+T)=f(x) for all x, then T is:", "options": ["period", "coefficient", "constant", "None"], "answer": 0},
        {"q": "If f(x)=x+x² is expanded in -π<x<π, then value of bn:", "options": ["none of above", "3", "1", "coefficient"], "answer": 0},
        {"q": "If f(x)=|x|, then f is a ......... function:", "options": ["odd", "even", "neither", "none"], "answer": 1},
        {"q": "A discontinuous function can be expanded using Fourier are:", "options": ["finite", "infinite", "uncountable", "none"], "answer": 0},
        {"q": "In the expansion of f(x)=x², bn is:", "options": ["0", "1", "-1", "None"], "answer": 0},
        {"q": "In expansion of f(x)=x²-2 in -2<x<2, value of bn is:", "options": ["-1", "1", "0", "None"], "answer": 2},
        {"q": "Half range cosine series of f(x) in 0<x<π contains:", "options": ["a₀ only", "a₀ and an", "bn only", "None"], "answer": 1},
        {"q": "Find constant a₀ of Fourier series of f(x)=k in interval 0 to 10:", "options": ["k", "2k", "k/2", "0"], "answer": 1},
        {"q": "Period of f(x)=x cos x in 0<x<2π:", "options": ["2π", "π", "4π", "None"], "answer": 0},
        {"q": "The period of f(x)=sin x cos 2x in 0<x<2π:", "options": ["2π", "π", "2π/n", "None"], "answer": 0},
        {"q": "Fourier coefficients a₀,an,bn are obtained by:", "options": ["Euler's Formula", "Maclaurin's Formula", "Taylor's Formula", "Laplace Formula"], "answer": 0},
        {"q": "Fourier coefficients a₀,an,bn in [-l,l] are obtained by:", "options": ["Fourier coefficients", "Laplace coefficients", "Taylor's coefficients", "Euler"], "answer": 0},
        {"q": "If f(x) is periodic with period ω=2l, Fourier coefficient:", "options": ["a₀=1/l ∫f(x)dx", "a₀=1/2l ∫f(x)dx", "a₀=2/l ∫f(x)dx", "None"], "answer": 0},
        {"q": "Fourier series of f(x) is Non-periodic?", "options": ["Periodic", "Non periodic", "Non differentiable", "Discontinuous"], "answer": 0},
        {"q": "In Fourier series, a₀,an,bn are obtained by:", "options": ["Euler's formula", "Taylor's formula", "Maclaurin's formula", "None"], "answer": 0},
        {"q": "If f(x) is periodic with period ω=2l then a₀=?", "options": ["4/(l) ∫0ˡ f(x)dx", "1/(b-a) ∫_aᵇ f(x)dx", "2/(b-a) ∫_aᵇ f(x)sinmx dx", "None"], "answer": 1},
        {"q": "In Fourier series of f(x), a₀,an,bn are called:", "options": ["Laplace", "Fourier coefficients", "Taylor", "None"], "answer": 1},
        {"q": "If f(x)=cos x in [-l,l], then Fourier coefficient bn is:", "options": ["Not", "l", "0", "None"], "answer": 2},
        {"q": "Fourier coefficients a₀,an,bn in 0 to π:", "options": ["an=1/l ∫f(x)cos(nπx/l)dx", "an=2/π ∫0π f(x)cos(nx)dx", "an=2l ∫f(x)cos(nx)dx", "None"], "answer": 1},
        {"q": "If f(x)=sin x·cos 2x then f(x) is:", "options": ["even", "odd", "Neither", "None"], "answer": 1},
        {"q": "If f(-x)=f(x), then f is periodic with period:", "options": ["2π", "π", "Neither", "None"], "answer": 0},
        {"q": "If f(x)=sin x·cos 2x in [-1,1], value of a₀ is:", "options": ["Not", "π", "2π", "None"], "answer": 0},
        {"q": "If f(x)=x is defined in [-1,1], then bn is:", "options": ["+1", "0", "-1", "None"], "answer": 1},
        {"q": "What is the Fourier series expansion of f(x)=x in 0<x<2π?", "options": ["Fourier series", "Fourier Cosine series", "Fourier Sine series", "None"], "answer": 0},
        {"q": "What is the period of f(x)=x is periodic in [0,2π]?", "options": ["2π", "π", "Not", "None"], "answer": 0},
        {"q": "Euler's formula gives:", "options": ["a₀,an,bn", "Derivative", "Integral", "None"], "answer": 0},
        {"q": "Half range sine series has only:", "options": ["an terms", "bn terms", "a₀+an terms", "None"], "answer": 1},
        {"q": "f(x) = sin x on [-π,π], value of a₀ is:", "options": ["0", "1", "2", "None"], "answer": 0},
        {"q": "f(x) = cos x on [-π,π], value of bn is:", "options": ["0", "1", "-1", "None"], "answer": 0},
        {"q": "In Fourier series of f(x)=x², the value of a₀ in [-π,π] is:", "options": ["2π²/3", "π²/3", "0", "2π"], "answer": 0},
        {"q": "For f(x) = constant k, value of bn is:", "options": ["0", "k", "k/n", "None"], "answer": 0},
        {"q": "For f(x) = |sinx|, the function is:", "options": ["even", "odd", "neither", "none"], "answer": 0},
        {"q": "Dirichlet's condition requires f to have:", "options": ["finite maxima and minima", "infinite discontinuities", "no discontinuities", "None"], "answer": 0},
        {"q": "Period of f(x) = sinx cosx is:", "options": ["π", "2π", "π/2", "4π"], "answer": 0},
        {"q": "Half range cosine series of f in 0 to π excludes:", "options": ["bn", "an", "a₀", "None"], "answer": 0},
        {"q": "What is a₀ for f(x)=1 on [-π,π]?", "options": ["1", "2", "0", "π"], "answer": 1},
        {"q": "Fourier series converges at point of discontinuity to:", "options": ["average of left and right limits", "left limit", "right limit", "None"], "answer": 0},
        {"q": "In expansion of f(x)=x in [-π,π], an=?", "options": ["0", "1/n", "2/nπ", "None"], "answer": 0}
    ]

    # UNIT 4: ODE BASICS (Q1-Q50)
    u4_questions = [
        {"q": "Order of DE: p' + 4p = sin x:", "options": ["1", "2", "3", "0"], "answer": 0},
        {"q": "Given DE: 1+(y')²=7(y'')³, write its order and degree:", "options": ["2,3", "3,2", "1,3", "2,1"], "answer": 0},
        {"q": "General solution of DE dy/dx = y/x is given by:", "options": ["log y = kx", "y = kx", "y = k log x", "log y = log x"], "answer": 1},
        {"q": "General solution of order 1 will involve how many constants?", "options": ["0", "1", "2", "3"], "answer": 1},
        {"q": "A differential equation is said to be ordinary if it involves:", "options": ["2 independent variables", "1 independent variable", "3 independent variables", "none"], "answer": 1},
        {"q": "A differential equation is said to be partial if it involves:", "options": ["2+ independent variables", "1 independent variable", "0 independent variables", "None"], "answer": 0},
        {"q": "Solution of 2x·y' - y = 3 represents:", "options": ["straight lines", "ellipses", "parabolas", "circles"], "answer": 2},
        {"q": "Integrating factor of DE cos x·dy/dx + y sin x = x²·y:", "options": ["sin x", "cos x", "sec x", "tan x"], "answer": 1},
        {"q": "Classify DE: e^(dy/dx) + 3y = x²:", "options": ["separable", "linear and not separable", "both", "none"], "answer": 1},
        {"q": "DE w(dw/dt) + 3t = 10 is:", "options": ["not separable", "not seperable", "both seperable and non linear", "not seperable not linear"], "answer": 2},
        {"q": "General solution of DE (y+c²) = cx where c is constant, order is:", "options": ["linear", "not linear", "non linear ODE", "none"], "answer": 1},
        {"q": "Differential equation y·y' = a-x represents:", "options": ["4", "1", "2", "3"], "answer": 0},
        {"q": "Time taken by particle moving x-axis according to dx/dt = x+4 to travel 96 units:", "options": ["2 ln 5", "2 ln 5 units", "ln 25", "5 ln 2"], "answer": 0},
        {"q": "Particular solution of DE involves:", "options": ["0 arbitrary constants", "1 arbitrary constants", "2 arbitrary constants", "None"], "answer": 0},
        {"q": "If x=2 in cot t and y=tan t+cot t, value of dy/dx is:", "options": ["0", "2", "cot 2t", "cos 2t"], "answer": 2},
        {"q": "Differential equation 2y'+(x²+3)y²=0 is:", "options": ["non linear", "linear", "exact", "bernoulli"], "answer": 3},
        {"q": "Degree of DE 2y'+x²y=0 is:", "options": ["non linear", "linear", "1", "2"], "answer": 2},
        {"q": "Degree of DE 2y'+x²y+sin(y')=0 is:", "options": ["not defined", "1", "2", "None"], "answer": 0},
        {"q": "The differential equation x²dy+y(x+y)dx=0 is:", "options": ["linear", "non homogeneous", "homogeneous", "Bernoulli"], "answer": 2},
        {"q": "A DE of form dy/dx+Py=Q is said to be a ..... DE:", "options": ["exact", "homogeneous", "Bernoulli", "linear"], "answer": 3},
        {"q": "The differential equation (1+4xy+2y²)dx+(1+4xy)dy=0 is:", "options": ["exact", "linear", "Bernoulli", "homogeneous"], "answer": 0},
        {"q": "A function which when multiplied to degree differential equation converts into first order exact is said to be:", "options": ["integrating factor", "general term", "arbitrary constant", "bernoulli"], "answer": 0},
        {"q": "Differential equation 2x²dy+2y dy=0 is:", "options": ["exact", "linear", "homogeneous", "Bernoulli"], "answer": 0},
        {"q": "Solution of x dx + y dy = 0 is:", "options": ["x=sin x-c cos x", "y=sin x+c cos x", "both exact and seperable", "none"], "answer": 2},
        {"q": "The order of the differential equation whose solution is y = A cos x + B sin x is:", "options": ["1", "2", "3", "4"], "answer": 1},
        {"q": "Solution of dy/dx+2y=x dx is:", "options": ["x=y+c", "x²-y²=c", "x-y=c", "None"], "answer": 1},
        {"q": "Value of bn is:", "options": ["-1", "+1", "0", "None"], "answer": 2},
        {"q": "Degree of homogeneous ODE (c²-y²)x + 3xy(dy/dx)=0 is:", "options": ["2", "Not", "1", "None"], "answer": 1},
        {"q": "For solenoidal field v, divergence is:", "options": ["Non zero", "Zero", "Never zero", "Not"], "answer": 1},
        {"q": "ODE y'=x is:", "options": ["Linear in y", "Non Linear in y", "Not Defined", "None"], "answer": 0},
        {"q": "f(x,y)=x²+y²+xy is homogeneous function of degree:", "options": ["Not defined", "2", "1", "0"], "answer": 1},
        {"q": "Order of ODE (dy/dx)²+|1+(dy/dx)³|=0 is:", "options": ["Not defined", "2", "1", "0"], "answer": 2},
        {"q": "ODE M dx + N dy = 0 is exact if:", "options": ["∂M/∂y=∂N/∂x", "∂M/∂x=∂N/∂y", "∂M/∂y≠∂N/∂x", "None"], "answer": 0},
        {"q": "∂y/∂x + Py = Qyⁿ is linear ODE if:", "options": ["n=0", "n=1", "n=-1", "None"], "answer": 0},
        {"q": "General solution of second-order homogeneous linear differential equation with constant coefficients has how many arbitrary constants?", "options": ["0", "1", "2", "3"], "answer": 2},
        {"q": "Solution of dy/dx = e^(x-y) is:", "options": ["eʸ = eˣ + c", "eʸ - eˣ = c", "eˣ + eʸ = c", "None"], "answer": 0},
        {"q": "The equation dy/dx = (x²+y²)/(2xy) is:", "options": ["linear", "exact", "homogeneous", "Bernoulli"], "answer": 2},
        {"q": "Integrating factor of x dy - y dx = 0 is:", "options": ["1/x", "1/x²", "1/y", "1/y²"], "answer": 1},
        {"q": "A Bernoulli equation dy/dx + Py = Qyⁿ is reduced by substituting:", "options": ["v = yⁿ", "v = y^(1-n)", "v = y^(n+1)", "v = 1/y"], "answer": 1},
        {"q": "The DE (2xy)dx + (x²-y²)dy = 0 is:", "options": ["exact", "linear", "Bernoulli", "homogeneous"], "answer": 0},
        {"q": "Order and degree of DE (y'')² + 3y' = x are respectively:", "options": ["2 and 2", "1 and 2", "2 and 1", "1 and 1"], "answer": 0},
        {"q": "If ∂M/∂y = ∂N/∂x then M dx + N dy = 0 is:", "options": ["linear", "Bernoulli", "exact", "homogeneous"], "answer": 2},
        {"q": "The degree of DE y'' + y = sin y' is:", "options": ["not defined", "1", "2", "0"], "answer": 0},
        {"q": "Integrating factor of dy/dx + y/x = x² is:", "options": ["x", "1/x", "x²", "1/x²"], "answer": 0},
        {"q": "The general solution of dy/dx = cos x is:", "options": ["y = sin x + c", "y = -sin x + c", "y = cos x + c", "None"], "answer": 0},
        {"q": "DE dy/dx = x/y represents family of:", "options": ["circles", "ellipses", "parabolas", "straight lines"], "answer": 0},
        {"q": "For DE (3x²+6xy)dx + (6x²y+4y³)dy = 0, it is:", "options": ["exact", "linear", "Bernoulli", "homogeneous"], "answer": 0},
        {"q": "The solution curve of y' = -y/x is:", "options": ["y = c/x", "y = cx", "y = cx²", "y = c/x²"], "answer": 0},
        {"q": "Linear DE of first order has the form dy/dx + Py =:", "options": ["Q", "Qyⁿ", "Py", "None"], "answer": 0},
        {"q": "Solution of exact DE M dx+N dy=0 is ∫M dx + ∫(terms of N not containing x)dy =:", "options": ["c", "0", "M", "None"], "answer": 0}
    ]

    # UNIT 5: HIGHER ORDER ODE (Q1-Q50)
    u5_questions = [
        {"q": "Order of the DE (Dⁿ + a1Dⁿ⁻¹+...+an)y=0 is:", "options": ["n", "n-1", "n+1", "None"], "answer": 0},
        {"q": "Part of solution of n-th order DE which involves n arbitrary constants is called:", "options": ["complementary function", "particular integral", "complete integral", "none"], "answer": 0},
        {"q": "The differential equation (D²+a1D+a2)y=Q is said to be homogeneous if Q is:", "options": ["0", "a function of y", "a function of x", "constant"], "answer": 0},
        {"q": "The equation mⁿ + a1mⁿ⁻¹+...+an=0 is the nth order linear DE is known as the … of the nth order linear DE:", "options": ["complementary equation", "auxiliary equation", "particular equation", "None"], "answer": 1},
        {"q": "The differential equation D²+a1D+a2y=0 is homogeneous if:", "options": ["integrating factor", "complementary function", "particular integral", "None"], "answer": 1},
        {"q": "Determine the degree of DE (Dⁿ + a1Dⁿ⁻²+...+an)y=0:", "options": ["n", "n-1", "2", "None"], "answer": 0},
        {"q": "The roots of characteristic equation of y''-7y'+12y=0:", "options": ["4,-1", "3,4", "7,-4", "None"], "answer": 1},
        {"q": "What is the particular integral of DE (D²+4y)=sin 3x?", "options": ["y=cos x", "y=-sin3x/5", "y=sin3x", "None"], "answer": 1},
        {"q": "Using method of undetermined coefficients, PI of xⁿ(t)-3e³ᵗ is:", "options": ["Ae³ᵗ", "general integral", "complete integral", "none"], "answer": 0},
        {"q": "If y=eᵃˣ is a solution of y'' - 5y' + ky = 0, then value of k is:", "options": ["2", "8", "4", "6"], "answer": 2},
        {"q": "Which of the following is a general solution of DE (d²y/dx²)+3(dy/dx)-10y=0?", "options": ["y=ae⁻⁵ˣ+be²ˣ", "y=ae²ˣ+be⁻⁵ˣ", "Both", "None"], "answer": 2},
        {"q": "Consider DE y''-7y=0, then roots of auxiliary equation:", "options": ["0 and 7", "there is no auxiliary eqn", "0 and -7", "None"], "answer": 0},
        {"q": "The DE x²y''-2y'+y=0 is a:", "options": ["Cauchy D.E.", "exact D.E.", "Legendre D.E.", "none"], "answer": 0},
        {"q": "What does the operator 1/D mean?", "options": ["∫dx", "d/dx", "None", "d²/dx²"], "answer": 0},
        {"q": "If roots of auxiliary equation are complex a±bi, CF contains the term:", "options": ["sin x", "eᵃˣ", "eᵃˣ(c1cos bx + c2sin bx)", "cos x"], "answer": 2},
        {"q": "PI of DE (D²-4)y=0 is:", "options": ["e²ˣ", "sin x", "0", "cos x"], "answer": 2},
        {"q": "To solve Euler Cauchy DE y'''-2xy''-2xy'+y'=e⁻³ˣ, substitution is:", "options": ["x=eᶻ", "x=log z", "x=z", "None"], "answer": 0},
        {"q": "The PI of equation y''=x²·y by method of undetermined coefficients, PI is assumed to be:", "options": ["ax", "ax²+bx+c", "ax²+b", "none"], "answer": 1},
        {"q": "CF of x²y''-2xy'+4y=0 is:", "options": ["ax+bx² sin x", "ax cos(ln x)+bx sin(ln x)", "c1eˣ+c2e⁻ˣ", "None"], "answer": 1},
        {"q": "Solution of D.E. y''+4y=sin 3x is:", "options": ["c1cos 2x+c2sin 2x+sin 3x/5", "c1cos 2x+c2sin 2x-sin3x/5", "c1cos 2x+c2sin 2x", "None"], "answer": 1},
        {"q": "Solution of (D²+4y)=sin 3x is:", "options": ["c1cos 3x+c2sin 3x", "c1cos 2x+c2sin 2x-sin3x/5", "c1cos 2x+c2sin 2x+sin3x/5", "None"], "answer": 1},
        {"q": "What does the CF of DE (D²+4)y=sin 3x is:", "options": ["c1cos x+c2sin x", "c1cos 2x+c2sin 2x", "c1e²ˣ+c2e⁻²ˣ", "None"], "answer": 1},
        {"q": "The roots of the auxiliary equation of y''-3y'-4y=0 are:", "options": ["3π/2", "π/2", "-3π/2", "None"], "answer": 0},
        {"q": "CF of y''+a²y=sin ax is:", "options": ["A cos ax+B sin ax", "Aeᵃˣ", "Ae⁻ᵃˣ+Beᵃˣ", "None"], "answer": 0},
        {"q": "If the auxiliary equation has exactly 5 roots, then what is the order of the differential equation?", "options": ["none of above", "2", "3", "5"], "answer": 3},
        {"q": "Term 'order' in a differential equation refers to:", "options": ["highest power", "highest power of derivative present", "number of constants", "number of terms"], "answer": 1},
        {"q": "Which condition indicates that the second-order linear non-homogeneous differential equation is homogeneous?", "options": ["The coefficients are constants", "The equation contains a non-zero constant term", "The coefficients are functions", "None"], "answer": 0},
        {"q": "The Wronskian of two solutions of second-order linear differential equation is zero if and only if:", "options": ["independent", "linearly dependent", "initial values provided", "no arbitrary constants"], "answer": 1},
        {"q": "Which condition ensures that the solution of second-order linear differential equation is unique?", "options": ["coefficients are constant", "no arbitrary constants", "non-homogeneous", "initial values provided"], "answer": 3},
        {"q": "In the method of finding undetermined coefficients, what do you assume for second-order non-homogeneous?", "options": ["A polynomial solution", "exponential solution", "logarithmic", "constant"], "answer": 0},
        {"q": "The complementary function of second-order linear differential equation is obtained by:", "options": ["Solving the corresponding homogeneous equation", "Taking derivative", "Multiplying solutions", "Adding particular solutions"], "answer": 0},
        {"q": "For a second-order linear non-homogeneous differential equation, what must be added to the CF to obtain general solution?", "options": ["Second derivative", "Constant term", "logarithmic", "Particular solution"], "answer": 3},
        {"q": "The Wronskian of two solutions of second-order linear differential equation is zero if:", "options": ["independent", "linearly dependent", "initial values provided", "non-homogeneous"], "answer": 1},
        {"q": "The term 'order' in a differential equation refers to:", "options": ["Highest power", "Highest order derivative", "Number of variables", "None"], "answer": 1},
        {"q": "If roots of auxiliary equation are equal (m=m1=m2), then CF is:", "options": ["(c1+c2x)eᵐ¹ˣ", "c1eᵐ¹ˣ+c2eᵐ²ˣ", "c1cos m1x+c2sin m1x", "None"], "answer": 0},
        {"q": "Method of variation of parameters is used for finding:", "options": ["CF", "PI", "both", "None"], "answer": 1},
        {"q": "The PI of 1/D² sin ax is:", "options": ["-sin ax/a²", "sin ax/a²", "cos ax/a", "None"], "answer": 0},
        {"q": "PI of 1/f(D) eᵃˣ when f(a)≠0 is:", "options": ["eᵃˣ/f(a)", "eᵃˣ·f(a)", "xeᵃˣ/f(a)", "None"], "answer": 0},
        {"q": "Cauchy-Euler equation x²y''+xy'+y=0 is solved by substitution:", "options": ["x=eᵗ", "x=log t", "x=t²", "None"], "answer": 0},
        {"q": "PI of (D²+1)y=sin x:", "options": ["-x cos x/2", "x sin x/2", "cos x", "None"], "answer": 0},
        {"q": "If CF of DE is c1e²ˣ+c2e⁻³ˣ, roots of AE are:", "options": ["2,-3", "-2,3", "2,3", "-2,-3"], "answer": 0},
        {"q": "For DE y''+y=0, the general solution is:", "options": ["c1cos x+c2sin x", "c1eˣ+c2e⁻ˣ", "c1+c2x", "None"], "answer": 0},
        {"q": "Particular integral of eˣ/D is:", "options": ["eˣ", "xeˣ", "eˣ/2", "None"], "answer": 0},
        {"q": "Order of Cauchy-Euler DE x²y''+xy'+y=f(x) is:", "options": ["1", "2", "3", "None"], "answer": 1},
        {"q": "1/D means:", "options": ["integration", "differentiation", "division", "None"], "answer": 0},
        {"q": "AE of y''-5y'+6y=0 is:", "options": ["m²-5m+6=0", "m²+5m+6=0", "m²-5m-6=0", "None"], "answer": 0},
        {"q": "Roots of AE m²-5m+6=0 are:", "options": ["2,3", "3,2", "Both A&B", "None"], "answer": 2},
        {"q": "CF when roots of AE are 2,3 is:", "options": ["c1e²ˣ+c2e³ˣ", "c1e⁻²ˣ+c2e⁻³ˣ", "c1cos2x+c2sin2x", "None"], "answer": 0},
        {"q": "PI of (D²-3D+2)y=eˣ is:", "options": ["xeˣ", "eˣ/f(a)", "x²eˣ/2", "None"], "answer": 0},
        {"q": "Degree of DE y''+sin(y')=0 is:", "options": ["not defined", "1", "2", "None"], "answer": 0}
    ]

    data = {
        "units": [
            {"id": 1, "title": "Complex Numbers", "summary": "Algebraic properties, De Moivre's Theorem, and complex functions.", "formulas": ["z = a + bi", "|z| = √(a² + b²)", "arg z = tan⁻¹(b/a)", "eⁱᶿ = cos θ + i sin θ"], "tips": ["Real part of iⁱ is e⁻ᴨ/²", "Arg of negative real is π"], "questions": u1_questions},
            {"id": 2, "title": "Vector Calculus", "summary": "Gradient, Divergence, Curl, and Vector integration.", "formulas": ["∇f = (∂f/∂x)i + (∂f/∂y)j + (∂f/∂z)k", "div F = ∇·F", "curl F = ∇×F"], "tips": ["div curl F = 0", "curl grad f = 0"], "questions": u2_questions},
            {"id": 3, "title": "Fourier Series", "summary": "Periodic functions, Even/Odd expansions, and Dirichlet conditions.", "formulas": ["f(x) = a₀/2 + Σ[aₙ cos(nx) + bₙ sin(nx)]", "aₙ = 1/π ∫f(x)cos(nx)dx"], "tips": ["Even: bn=0", "Odd: an=0"], "questions": u3_questions},
            {"id": 4, "title": "ODE Basics", "summary": "First-order equations, Integrating factors, and Exactness.", "formulas": ["IF = e^(∫Pdx)", "Mdx + Ndy = 0"], "tips": ["Check ∂M/∂y = ∂N/∂x", "Degree vs Order"], "questions": u4_questions},
            {"id": 5, "title": "Higher Order ODE", "summary": "Linear equations with constant coefficients, CF and PI.", "formulas": ["GS = CF + PI", "PI for eᵃˣ = 1/f(a) eᵃˣ"], "tips": ["Roots define CF", "Variation of Parameters"], "questions": u5_questions}
        ],
        "most_important": [
            "Euler's Identity for Unit 1",
            "Solenoidal definition in Unit 2",
            "Dirichlet conditions in Unit 3",
            "Integrating Factors for Unit 4",
            "CF calculation for Unit 5"
        ]
    }
    return data

data = get_math_data()
print("const MATH_DATA = " + json.dumps(data, indent=2) + ";")
